### ISSUE TITLE
Password Requirement Documentation

### ISSUE THREAD

**Issue by woodydeck** [hiviah/TrezorPass#3]
It would be very nice to understand why the database needs an additional password. Is there an attack vector if you leave it blank?

![screenshot 2015-11-04 21 58 33](https://cloud.githubusercontent.com/assets/13375011/10961053/3ababc86-833f-11e5-8197-9486456b1575.png)

**Comment by hiviah** [comment]
Originally, it was meant that Trezor was used with passphrase and not PIN when used together with TrezorPass. You should use either passphrase or PIN, or both.

I personally think passphrase is safer, because it enters the key derivation mechanism on Trezor. Thus in case of a side channel leak from the hardware the attacker still won't have all of the required secret data to recreate decryption key.

**Comment by woodydeck** [comment]
Makes sense, and this is what I surmised, but couldn't confirm without your input. Thank you!

It would be great if the Trezor could be integrated with a fork of the TrueCrypt project. I am hoping to do that in the future if nobody comes up with a better encryption solution. The Trezor stops keyloggers in their tracks, and having an encrypted volume protected by a Trezor improves security massively when you can just drag and drop a file somewhere, say to a sterile VM.

For now, I am grateful to have your application, even if I am sad that not enough people paid it attention. With the hack of LastPass, it is very clear that having anything other than a hardware solution like Trezor to login into any account is a very big security risk.

I am very happy with the simple nature of this program. It works well. Thanks again.

**Comment by hiviah** [comment]
I am skeptical about using Trezor for full disk encryption (be it TrueCrypt or LUKS). The reason is there is no C API that can be used for example in grub or TrueCrypt. I think you could use the python version with a bit hacking, similar to this [2-factor LUKS FDE with Yubikey](https://github.com/cornelinux/yubikey-luks). Note that the Yubikey usage is far from perfect, as it actually sends just HMAC-SHA1(password) of the original password as the second factor (this holds true for the old Yubikey without GPG applet).

You might also have look at the new [Yubikey Neo](https://www.yubico.com/products/yubikey-hardware/yubikey-neo/), which supports GPG and also U2F (universal 2-factor, also resistant to malware and keyloggers). Unfortunately it seems that U2F, even if it uses secp256r1 curve, can be only used for authenthication, not encryption. I haven't had time to go through the full specifications yet, just got the Neo with U2F few days ago.

The great plus side of Yubikey Neo is that there are already [libraries available for working with it](https://github.com/Yubico). It also uses hidraw protocol, similar to Trezor.
